import type { NewCandidate, NewTweet } from "./db/schema";

interface SeedProfile {
  candidate: Omit<NewCandidate, "id">;
  tweets: Omit<NewTweet, "id" | "candidateId">[];
}

function avatar(seed: string) {
  return `https://api.dicebear.com/7.x/notionists/svg?seed=${seed}`;
}

export const SEED_PROFILES: SeedProfile[] = [
  {
    candidate: {
      twitterId: "seed_001",
      username: "alexchen_ai",
      displayName: "Alex Chen",
      bio: "Building AI-native dev tools. Ex-Google. YC W24. Ship fast, learn faster.",
      avatarUrl: avatar("alexchen"),
      followerCount: 12400,
      followingCount: 890,
      tweetCount: 3200,
      accountCreatedAt: "2019-03-15T00:00:00Z",
      pipelineStage: "discovered",
      overallScore: 87,
      builderScore: 92,
      authenticityScore: 85,
      growthScore: 80,
      redFlagScore: 5,
    },
    tweets: [
      { tweetId: "t001a", text: "Just shipped v2 of our AI code review tool. 3x faster inference, context window went from 8K to 128K tokens. The architecture rewrite was painful but worth it.", likes: 342, retweets: 45, replies: 28, views: 18000, isRetweet: false, isReply: false, createdAt: "2026-02-18T14:00:00Z" },
      { tweetId: "t001b", text: "Lesson learned: don't try to fine-tune your way out of a prompting problem. Spent 2 weeks on fine-tuning when a better system prompt would have solved it in an hour.", likes: 891, retweets: 120, replies: 67, views: 45000, isRetweet: false, isReply: false, createdAt: "2026-02-15T10:00:00Z" },
      { tweetId: "t001c", text: "Our RAG pipeline now handles 50K docs with sub-200ms latency. Key insight: hierarchical chunking + semantic caching. Blog post coming soon.", likes: 234, retweets: 38, replies: 19, views: 12000, isRetweet: false, isReply: false, createdAt: "2026-02-10T16:00:00Z" },
      { tweetId: "t001d", text: "Hit 1000 paying users today. Started this 8 months ago in my apartment. Wild journey.", likes: 1200, retweets: 89, replies: 156, views: 62000, isRetweet: false, isReply: false, createdAt: "2026-02-05T09:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_002",
      username: "priya_builds",
      displayName: "Priya Sharma",
      bio: "ML engineer → founder. Building autonomous agents for enterprise. Prev: Meta AI Research.",
      avatarUrl: avatar("priya"),
      followerCount: 8700,
      followingCount: 1200,
      tweetCount: 2100,
      accountCreatedAt: "2020-06-10T00:00:00Z",
      pipelineStage: "researching",
      overallScore: 82,
      builderScore: 88,
      authenticityScore: 78,
      growthScore: 82,
      redFlagScore: 8,
    },
    tweets: [
      { tweetId: "t002a", text: "Launched our agent framework today. It lets you build multi-step AI workflows with built-in tool use and memory. Open source.", likes: 456, retweets: 78, replies: 34, views: 23000, isRetweet: false, isReply: false, createdAt: "2026-02-17T11:00:00Z" },
      { tweetId: "t002b", text: "The biggest mistake in agent design: giving the LLM too many tools at once. Constrain the action space per step. Your success rate will jump 40%.", likes: 678, retweets: 95, replies: 45, views: 35000, isRetweet: false, isReply: false, createdAt: "2026-02-12T15:00:00Z" },
      { tweetId: "t002c", text: "Just closed our seed round. $2.5M to build the future of enterprise automation. Grateful for the team and investors who believe in this.", likes: 890, retweets: 67, replies: 123, views: 42000, isRetweet: false, isReply: false, createdAt: "2026-02-08T09:00:00Z" },
      { tweetId: "t002d", text: "Interesting finding: GPT-4 class models are overkill for 80% of agent tasks. A well-prompted Haiku or small model handles routing, extraction, and classification just fine.", likes: 345, retweets: 56, replies: 28, views: 18000, isRetweet: false, isReply: false, createdAt: "2026-02-03T14:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_003",
      username: "marcusdev_",
      displayName: "Marcus Johnson",
      bio: "Full-stack + AI. Building tools that make developers 10x more productive. Shipping every week.",
      avatarUrl: avatar("marcus"),
      followerCount: 5200,
      followingCount: 780,
      tweetCount: 4500,
      accountCreatedAt: "2018-11-22T00:00:00Z",
      pipelineStage: "discovered",
      overallScore: 78,
      builderScore: 85,
      authenticityScore: 72,
      growthScore: 75,
      redFlagScore: 10,
    },
    tweets: [
      { tweetId: "t003a", text: "Built an AI-powered CLI that auto-generates database migrations from natural language. 'Add a users table with email and created_at' → perfect SQL migration.", likes: 234, retweets: 45, replies: 19, views: 12000, isRetweet: false, isReply: false, createdAt: "2026-02-19T08:00:00Z" },
      { tweetId: "t003b", text: "Week 12 of building in public: shipped the VS Code extension. 200 installs on day 1. Not viral, but real people using it daily. That's what matters.", likes: 178, retweets: 23, replies: 34, views: 8900, isRetweet: false, isReply: false, createdAt: "2026-02-14T12:00:00Z" },
      { tweetId: "t003c", text: "Hot take: the best AI products don't feel like AI products. They feel like magic autocomplete for whatever you're already doing.", likes: 567, retweets: 89, replies: 45, views: 28000, isRetweet: false, isReply: false, createdAt: "2026-02-09T16:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_004",
      username: "sarahml_",
      displayName: "Sarah Kim",
      bio: "PhD dropout → AI startup founder. Fine-tuning specialist. Making LLMs actually useful for healthcare.",
      avatarUrl: avatar("sarah"),
      followerCount: 15600,
      followingCount: 450,
      tweetCount: 1800,
      accountCreatedAt: "2021-01-05T00:00:00Z",
      pipelineStage: "outreach_ready",
      overallScore: 91,
      builderScore: 95,
      authenticityScore: 90,
      growthScore: 85,
      redFlagScore: 3,
    },
    tweets: [
      { tweetId: "t004a", text: "Our medical LLM just passed the USMLE Step 1 with 92% accuracy. Fine-tuned on 500K clinical notes with physician oversight. This is going to change how doctors learn.", likes: 2300, retweets: 340, replies: 189, views: 120000, isRetweet: false, isReply: false, createdAt: "2026-02-20T10:00:00Z" },
      { tweetId: "t004b", text: "Released our clinical NER model on HuggingFace. It identifies medications, dosages, and conditions with 96% F1. Free for research use.", likes: 890, retweets: 156, replies: 67, views: 45000, isRetweet: false, isReply: false, createdAt: "2026-02-13T09:00:00Z" },
      { tweetId: "t004c", text: "After 6 months of working with hospitals, the #1 lesson: AI in healthcare isn't a tech problem, it's a trust problem. Every feature needs explainability.", likes: 1456, retweets: 234, replies: 98, views: 78000, isRetweet: false, isReply: false, createdAt: "2026-02-06T14:00:00Z" },
      { tweetId: "t004d", text: "Hiring ML engineers who care about healthcare outcomes, not just benchmarks. Remote, competitive comp, meaningful work. DM me.", likes: 345, retweets: 89, replies: 56, views: 18000, isRetweet: false, isReply: false, createdAt: "2026-01-28T11:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_005",
      username: "jakethebuilder",
      displayName: "Jake Morrison",
      bio: "Serial builder. 3rd startup. AI-powered analytics for e-commerce. Previously sold company to Shopify.",
      avatarUrl: avatar("jake"),
      followerCount: 22000,
      followingCount: 1100,
      tweetCount: 6700,
      accountCreatedAt: "2016-08-12T00:00:00Z",
      pipelineStage: "contacted",
      overallScore: 85,
      builderScore: 90,
      authenticityScore: 82,
      growthScore: 78,
      redFlagScore: 7,
    },
    tweets: [
      { tweetId: "t005a", text: "Shipped a feature that predicts which products will trend 2 weeks before they do. Using a mix of social signals + purchase data + LLM analysis. Accuracy: 73% so far.", likes: 567, retweets: 89, replies: 45, views: 29000, isRetweet: false, isReply: false, createdAt: "2026-02-18T13:00:00Z" },
      { tweetId: "t005b", text: "Building a startup for the 3rd time hits different. You skip so many mistakes. But you also know how hard it gets. That knowledge is both a blessing and a curse.", likes: 1200, retweets: 145, replies: 89, views: 62000, isRetweet: false, isReply: false, createdAt: "2026-02-11T10:00:00Z" },
      { tweetId: "t005c", text: "Our AI just saved a D2C brand $240K in ad spend by identifying that 3 of their top 10 SKUs were cannibalizing each other. No human analyst caught this.", likes: 890, retweets: 123, replies: 67, views: 45000, isRetweet: false, isReply: false, createdAt: "2026-02-04T15:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_006",
      username: "emilyz_codes",
      displayName: "Emily Zhang",
      bio: "Building AI writing tools. Passionate about making tech accessible. Prev: Notion, Figma.",
      avatarUrl: avatar("emily"),
      followerCount: 6800,
      followingCount: 920,
      tweetCount: 2900,
      accountCreatedAt: "2020-03-20T00:00:00Z",
      pipelineStage: "discovered",
      overallScore: 74,
      builderScore: 78,
      authenticityScore: 75,
      growthScore: 70,
      redFlagScore: 8,
    },
    tweets: [
      { tweetId: "t006a", text: "Just launched our AI writing assistant on Product Hunt. It doesn't just write for you — it teaches you to write better. Think Grammarly meets a writing coach.", likes: 234, retweets: 45, replies: 34, views: 12000, isRetweet: false, isReply: false, createdAt: "2026-02-16T08:00:00Z" },
      { tweetId: "t006b", text: "The secret to good AI UX: never make the user feel stupid. If the AI is smarter than the user, hide it. Make them feel like THEY had the insight.", likes: 456, retweets: 67, replies: 28, views: 23000, isRetweet: false, isReply: false, createdAt: "2026-02-10T14:00:00Z" },
      { tweetId: "t006c", text: "Iterated on our onboarding 7 times this month. Activation rate went from 23% to 61%. The key? Showing value in under 30 seconds.", likes: 345, retweets: 56, replies: 23, views: 17000, isRetweet: false, isReply: false, createdAt: "2026-02-03T11:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_007",
      username: "dev_omar",
      displayName: "Omar Hassan",
      bio: "Open source contributor. Building vector search infrastructure. Rust + Python. 🦀",
      avatarUrl: avatar("omar"),
      followerCount: 3400,
      followingCount: 560,
      tweetCount: 1500,
      accountCreatedAt: "2021-07-14T00:00:00Z",
      pipelineStage: "discovered",
      overallScore: 71,
      builderScore: 80,
      authenticityScore: 70,
      growthScore: 65,
      redFlagScore: 6,
    },
    tweets: [
      { tweetId: "t007a", text: "Released v0.3 of my vector search engine written in Rust. 10x faster than FAISS for datasets under 1M vectors. Benchmarks in thread.", likes: 189, retweets: 34, replies: 23, views: 9800, isRetweet: false, isReply: false, createdAt: "2026-02-19T15:00:00Z" },
      { tweetId: "t007b", text: "TIL: HNSW index parameters matter way more than the embedding model for retrieval quality. Spent a week tuning models when I should have tuned ef_construction.", likes: 123, retweets: 19, replies: 14, views: 6200, isRetweet: false, isReply: false, createdAt: "2026-02-12T09:00:00Z" },
      { tweetId: "t007c", text: "PR merged into LangChain adding native support for my vector store. Open source contributions → distribution → users. The playbook works.", likes: 267, retweets: 45, replies: 19, views: 13000, isRetweet: false, isReply: false, createdAt: "2026-02-05T16:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_008",
      username: "lisa_aiagent",
      displayName: "Lisa Park",
      bio: "AI agents for customer support. Making boring enterprise software actually intelligent. Techstars '25.",
      avatarUrl: avatar("lisa"),
      followerCount: 4100,
      followingCount: 670,
      tweetCount: 1900,
      accountCreatedAt: "2022-02-08T00:00:00Z",
      pipelineStage: "researching",
      overallScore: 76,
      builderScore: 82,
      authenticityScore: 73,
      growthScore: 72,
      redFlagScore: 9,
    },
    tweets: [
      { tweetId: "t008a", text: "Our AI agent just handled its first 1000 support tickets without human intervention. Resolution rate: 89%. Average handle time: 45 seconds (was 8 minutes).", likes: 345, retweets: 56, replies: 28, views: 18000, isRetweet: false, isReply: false, createdAt: "2026-02-17T10:00:00Z" },
      { tweetId: "t008b", text: "The hardest part of building AI agents for enterprise: handling the 11% of cases they can't solve gracefully. Escalation UX is everything.", likes: 198, retweets: 34, replies: 23, views: 10000, isRetweet: false, isReply: false, createdAt: "2026-02-11T14:00:00Z" },
      { tweetId: "t008c", text: "Pivoted from B2C to B2B three months ago. Best decision we made. Enterprise customers give better feedback, pay more, and churn less.", likes: 234, retweets: 45, replies: 34, views: 12000, isRetweet: false, isReply: false, createdAt: "2026-02-04T09:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_009",
      username: "techbro_ryan",
      displayName: "Ryan Motivates",
      bio: "AI entrepreneur | 10x mindset | Follow me for daily AI tips | DM for coaching 📈",
      avatarUrl: avatar("ryan"),
      followerCount: 45000,
      followingCount: 12000,
      tweetCount: 15000,
      accountCreatedAt: "2023-06-01T00:00:00Z",
      pipelineStage: "discovered",
      overallScore: 22,
      builderScore: 15,
      authenticityScore: 20,
      growthScore: 35,
      redFlagScore: 65,
    },
    tweets: [
      { tweetId: "t009a", text: "AI will create more millionaires in 2026 than any year in history. Are you positioned? DM me for my free course. 🧵", likes: 890, retweets: 234, replies: 156, views: 89000, isRetweet: false, isReply: false, createdAt: "2026-02-20T07:00:00Z" },
      { tweetId: "t009b", text: "Follow me for daily AI tips that will 10x your productivity. Like if you agree! RT to help others.", likes: 567, retweets: 189, replies: 89, views: 45000, isRetweet: false, isReply: false, createdAt: "2026-02-15T08:00:00Z" },
      { tweetId: "t009c", text: "The grind never stops. Rise and grind. No days off. Building an AI empire. Who's with me? 💪", likes: 345, retweets: 123, replies: 67, views: 23000, isRetweet: false, isReply: false, createdAt: "2026-02-10T06:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_010",
      username: "nina_nlp",
      displayName: "Nina Kowalski",
      bio: "NLP researcher turned founder. Building real-time translation for video calls. Ex-DeepMind.",
      avatarUrl: avatar("nina"),
      followerCount: 11200,
      followingCount: 680,
      tweetCount: 2400,
      accountCreatedAt: "2019-09-18T00:00:00Z",
      pipelineStage: "outreach_ready",
      overallScore: 88,
      builderScore: 91,
      authenticityScore: 88,
      growthScore: 83,
      redFlagScore: 4,
    },
    tweets: [
      { tweetId: "t010a", text: "Demo day: our real-time translation now works in 47 languages with <300ms latency. The trick was distilling our large model into a streaming-friendly architecture.", likes: 1200, retweets: 189, replies: 89, views: 62000, isRetweet: false, isReply: false, createdAt: "2026-02-19T11:00:00Z" },
      { tweetId: "t010b", text: "Published our paper on streaming translation with speculative decoding. 4x throughput improvement. ArXiv link in reply.", likes: 567, retweets: 89, replies: 45, views: 29000, isRetweet: false, isReply: false, createdAt: "2026-02-13T14:00:00Z" },
      { tweetId: "t010c", text: "From research to product: the gap is enormous. A model that works in a notebook is 10% of the work. The other 90% is latency, reliability, edge cases, and UX.", likes: 890, retweets: 134, replies: 67, views: 45000, isRetweet: false, isReply: false, createdAt: "2026-02-07T10:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_011",
      username: "danielrusso_",
      displayName: "Daniel Russo",
      bio: "Computer vision + robotics. Building autonomous inspection drones. MIT '22.",
      avatarUrl: avatar("daniel"),
      followerCount: 2800,
      followingCount: 430,
      tweetCount: 980,
      accountCreatedAt: "2022-05-20T00:00:00Z",
      pipelineStage: "discovered",
      overallScore: 68,
      builderScore: 75,
      authenticityScore: 68,
      growthScore: 60,
      redFlagScore: 5,
    },
    tweets: [
      { tweetId: "t011a", text: "Our drone just completed its first fully autonomous bridge inspection. 45 minutes, 2000+ images, zero human intervention. CV model caught 3 cracks the human inspectors missed.", likes: 234, retweets: 45, replies: 23, views: 12000, isRetweet: false, isReply: false, createdAt: "2026-02-18T09:00:00Z" },
      { tweetId: "t011b", text: "Training data for infrastructure defects is surprisingly hard to get. We ended up partnering with 5 civil engineering firms to build our dataset. Took 4 months.", likes: 123, retweets: 19, replies: 14, views: 6200, isRetweet: false, isReply: false, createdAt: "2026-02-10T13:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_012",
      username: "mei_wang_ai",
      displayName: "Mei Wang",
      bio: "AI for education. Personalized tutoring that actually works. Stanford CS → founder.",
      avatarUrl: avatar("mei"),
      followerCount: 7500,
      followingCount: 890,
      tweetCount: 2200,
      accountCreatedAt: "2020-11-03T00:00:00Z",
      pipelineStage: "in_conversation",
      overallScore: 83,
      builderScore: 86,
      authenticityScore: 82,
      growthScore: 79,
      redFlagScore: 6,
    },
    tweets: [
      { tweetId: "t012a", text: "Our AI tutor just helped 500 students improve their math scores by an average of 23%. Not by giving answers — by asking better questions.", likes: 678, retweets: 98, replies: 56, views: 35000, isRetweet: false, isReply: false, createdAt: "2026-02-19T10:00:00Z" },
      { tweetId: "t012b", text: "Built a new adaptive learning algorithm that adjusts difficulty in real-time based on response patterns. It detects confusion before the student does.", likes: 345, retweets: 56, replies: 28, views: 18000, isRetweet: false, isReply: false, createdAt: "2026-02-12T11:00:00Z" },
      { tweetId: "t012c", text: "Raised our Series A. $8M to bring AI tutoring to underserved school districts. Education should not be a luxury.", likes: 1200, retweets: 178, replies: 98, views: 62000, isRetweet: false, isReply: false, createdAt: "2026-02-01T09:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_013",
      username: "crypto_ai_max",
      displayName: "Max DeFi",
      bio: "AI x Crypto x Web3. Building the future of decentralized intelligence. NFA. DYOR. 🚀",
      avatarUrl: avatar("max"),
      followerCount: 28000,
      followingCount: 8900,
      tweetCount: 12000,
      accountCreatedAt: "2023-01-15T00:00:00Z",
      pipelineStage: "discovered",
      overallScore: 28,
      builderScore: 20,
      authenticityScore: 25,
      growthScore: 40,
      redFlagScore: 55,
    },
    tweets: [
      { tweetId: "t013a", text: "AI + crypto is the biggest opportunity of the decade. Our token launch is coming. Join the whitelist. Link in bio. 🚀🚀🚀", likes: 456, retweets: 234, replies: 189, views: 45000, isRetweet: false, isReply: false, createdAt: "2026-02-20T06:00:00Z" },
      { tweetId: "t013b", text: "GM! Who's bullish on AI tokens today? Drop your favorite AI crypto project below. Like + RT for visibility!", likes: 345, retweets: 178, replies: 234, views: 34000, isRetweet: false, isReply: false, createdAt: "2026-02-16T07:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_014",
      username: "rachel_devtools",
      displayName: "Rachel Torres",
      bio: "Dev tools founder. AI-powered testing that finds bugs before your users do. Prev: Stripe.",
      avatarUrl: avatar("rachel"),
      followerCount: 9300,
      followingCount: 720,
      tweetCount: 2800,
      accountCreatedAt: "2019-12-01T00:00:00Z",
      pipelineStage: "researching",
      overallScore: 80,
      builderScore: 84,
      authenticityScore: 80,
      growthScore: 76,
      redFlagScore: 7,
    },
    tweets: [
      { tweetId: "t014a", text: "Shipped our AI test generator today. Point it at your codebase, it writes integration tests that actually catch real bugs. Not toy examples.", likes: 456, retweets: 67, replies: 34, views: 23000, isRetweet: false, isReply: false, createdAt: "2026-02-18T10:00:00Z" },
      { tweetId: "t014b", text: "Interesting stat from our beta: AI-generated tests found 34% more edge case bugs than human-written tests. But humans wrote better happy path tests.", likes: 678, retweets: 89, replies: 45, views: 35000, isRetweet: false, isReply: false, createdAt: "2026-02-11T15:00:00Z" },
      { tweetId: "t014c", text: "The hardest part of building dev tools: developers are your harshest critics. They'll roast your product publicly if it wastes 5 minutes of their time.", likes: 345, retweets: 56, replies: 28, views: 18000, isRetweet: false, isReply: false, createdAt: "2026-02-05T11:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_015",
      username: "tom_audioai",
      displayName: "Tom Nguyen",
      bio: "Audio AI researcher. Building real-time voice cloning & synthesis. Ex-Spotify. Making podcasts easier.",
      avatarUrl: avatar("tom"),
      followerCount: 4600,
      followingCount: 580,
      tweetCount: 1600,
      accountCreatedAt: "2021-04-15T00:00:00Z",
      pipelineStage: "discovered",
      overallScore: 72,
      builderScore: 78,
      authenticityScore: 71,
      growthScore: 68,
      redFlagScore: 7,
    },
    tweets: [
      { tweetId: "t015a", text: "Launched our voice cloning API. 3 seconds of audio → a voice clone that's 95% MOS accurate. Ethical use only, with built-in consent verification.", likes: 234, retweets: 45, replies: 23, views: 12000, isRetweet: false, isReply: false, createdAt: "2026-02-17T14:00:00Z" },
      { tweetId: "t015b", text: "Built a real-time audio translation demo: speak English, hear yourself in Japanese with your own voice. Latency is ~400ms. Getting close to real-time.", likes: 567, retweets: 89, replies: 45, views: 29000, isRetweet: false, isReply: false, createdAt: "2026-02-09T11:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_016",
      username: "aisha_ml",
      displayName: "Aisha Okonkwo",
      bio: "ML for climate tech. Satellite imagery + AI to track deforestation in real time. Impact > profit.",
      avatarUrl: avatar("aisha"),
      followerCount: 6200,
      followingCount: 510,
      tweetCount: 1400,
      accountCreatedAt: "2021-09-10T00:00:00Z",
      pipelineStage: "outreach_ready",
      overallScore: 79,
      builderScore: 83,
      authenticityScore: 80,
      growthScore: 73,
      redFlagScore: 5,
    },
    tweets: [
      { tweetId: "t016a", text: "Our satellite ML model detected 23 illegal logging operations in the Amazon this month. Data shared with enforcement agencies. AI doing real good.", likes: 890, retweets: 156, replies: 67, views: 45000, isRetweet: false, isReply: false, createdAt: "2026-02-18T12:00:00Z" },
      { tweetId: "t016b", text: "Trained a segmentation model on 50K satellite images to classify land use changes. Accuracy: 94%. Open sourcing the model next week.", likes: 345, retweets: 67, replies: 28, views: 18000, isRetweet: false, isReply: false, createdAt: "2026-02-11T10:00:00Z" },
      { tweetId: "t016c", text: "Climate tech doesn't get enough AI attention. The models and techniques exist. We just need more builders applying them to environmental problems.", likes: 567, retweets: 89, replies: 45, views: 29000, isRetweet: false, isReply: false, createdAt: "2026-02-03T15:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_017",
      username: "kevin_ships",
      displayName: "Kevin Li",
      bio: "Indie hacker. Built 4 AI micro-SaaS products. $12K MRR. Building in public.",
      avatarUrl: avatar("kevin"),
      followerCount: 3100,
      followingCount: 890,
      tweetCount: 3400,
      accountCreatedAt: "2020-08-22T00:00:00Z",
      pipelineStage: "discovered",
      overallScore: 65,
      builderScore: 72,
      authenticityScore: 62,
      growthScore: 60,
      redFlagScore: 12,
    },
    tweets: [
      { tweetId: "t017a", text: "Launched my 4th AI product this year. AI-powered invoice processor for freelancers. Snap a photo → structured data. $29/mo.", likes: 123, retweets: 19, replies: 14, views: 6200, isRetweet: false, isReply: false, createdAt: "2026-02-16T09:00:00Z" },
      { tweetId: "t017b", text: "Monthly revenue update: $12,400 MRR across all products. Goal is $20K by June. The power of multiple income streams.", likes: 234, retweets: 34, replies: 23, views: 12000, isRetweet: false, isReply: false, createdAt: "2026-02-08T10:00:00Z" },
      { tweetId: "t017c", text: "Follow me for daily updates on building AI SaaS products. I share everything: revenue, code, mistakes, wins. 🧵 1/", likes: 89, retweets: 23, replies: 12, views: 4500, isRetweet: false, isReply: false, createdAt: "2026-02-02T08:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_018",
      username: "julia_robotics",
      displayName: "Julia Fernandez",
      bio: "Robotics + foundation models. Teaching robots to understand the world. PhD @ CMU. Building Spatial AI.",
      avatarUrl: avatar("julia"),
      followerCount: 8900,
      followingCount: 620,
      tweetCount: 1700,
      accountCreatedAt: "2020-01-15T00:00:00Z",
      pipelineStage: "contacted",
      overallScore: 84,
      builderScore: 88,
      authenticityScore: 84,
      growthScore: 79,
      redFlagScore: 5,
    },
    tweets: [
      { tweetId: "t018a", text: "Our robot just learned to fold laundry from watching 100 YouTube videos + a VLM backbone. No task-specific training. Zero-shot generalization is getting real.", likes: 1200, retweets: 189, replies: 89, views: 62000, isRetweet: false, isReply: false, createdAt: "2026-02-19T13:00:00Z" },
      { tweetId: "t018b", text: "Published our work on spatial reasoning in foundation models. Key finding: multimodal models are surprisingly good at 3D understanding with the right prompting.", likes: 456, retweets: 78, replies: 34, views: 23000, isRetweet: false, isReply: false, createdAt: "2026-02-13T10:00:00Z" },
      { tweetId: "t018c", text: "Leaving academia to go full-time on Spatial AI. The gap between research capabilities and real-world robotics is a startup opportunity.", likes: 678, retweets: 98, replies: 67, views: 35000, isRetweet: false, isReply: false, createdAt: "2026-02-06T11:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_019",
      username: "sam_genai",
      displayName: "Sam Patel",
      bio: "GenAI for legal. Automating contract review and due diligence. Lawyer turned coder.",
      avatarUrl: avatar("sam"),
      followerCount: 5400,
      followingCount: 780,
      tweetCount: 2100,
      accountCreatedAt: "2021-03-05T00:00:00Z",
      pipelineStage: "discovered",
      overallScore: 73,
      builderScore: 79,
      authenticityScore: 72,
      growthScore: 68,
      redFlagScore: 8,
    },
    tweets: [
      { tweetId: "t019a", text: "Our AI contract reviewer just processed 500 NDAs in 2 hours. Would have taken a junior associate 2 weeks. Found 12 non-standard clauses humans missed.", likes: 345, retweets: 56, replies: 28, views: 18000, isRetweet: false, isReply: false, createdAt: "2026-02-17T11:00:00Z" },
      { tweetId: "t019b", text: "The legal industry is 5 years behind on AI adoption. That's not a bug — it's a massive opportunity for founders who understand both domains.", likes: 234, retweets: 45, replies: 23, views: 12000, isRetweet: false, isReply: false, createdAt: "2026-02-09T14:00:00Z" },
      { tweetId: "t019c", text: "Built a fine-tuned model for legal entity extraction. Trained on 100K contracts. F1 score: 97.2% on entity recognition. Open sourcing the evaluation benchmark.", likes: 178, retweets: 34, replies: 19, views: 9000, isRetweet: false, isReply: false, createdAt: "2026-02-02T10:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_020",
      username: "grace_ml_ops",
      displayName: "Grace Liu",
      bio: "MLOps & infra. Making ML deployment less painful. Open source advocate. Building at scale.",
      avatarUrl: avatar("grace"),
      followerCount: 7100,
      followingCount: 540,
      tweetCount: 1900,
      accountCreatedAt: "2020-06-20T00:00:00Z",
      pipelineStage: "researching",
      overallScore: 77,
      builderScore: 82,
      authenticityScore: 76,
      growthScore: 73,
      redFlagScore: 7,
    },
    tweets: [
      { tweetId: "t020a", text: "Released our ML deployment framework. Go from notebook to production API in 3 commands. Handles scaling, monitoring, and rollbacks automatically.", likes: 456, retweets: 78, replies: 34, views: 23000, isRetweet: false, isReply: false, createdAt: "2026-02-18T11:00:00Z" },
      { tweetId: "t020b", text: "Hot take: most ML failures in production aren't model failures. They're data pipeline failures. Invest in data quality before model quality.", likes: 678, retweets: 98, replies: 45, views: 35000, isRetweet: false, isReply: false, createdAt: "2026-02-12T14:00:00Z" },
      { tweetId: "t020c", text: "Our open source project hit 5K GitHub stars. Community contributions are now 40% of all PRs. This is how you build sustainable OSS.", likes: 345, retweets: 56, replies: 28, views: 18000, isRetweet: false, isReply: false, createdAt: "2026-02-05T10:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_021",
      username: "ben_biomed",
      displayName: "Ben Williams",
      bio: "AI for drug discovery. Using transformers to predict protein interactions. Biotech x ML.",
      avatarUrl: avatar("ben"),
      followerCount: 4800,
      followingCount: 390,
      tweetCount: 1200,
      accountCreatedAt: "2021-11-10T00:00:00Z",
      pipelineStage: "discovered",
      overallScore: 70,
      builderScore: 76,
      authenticityScore: 72,
      growthScore: 62,
      redFlagScore: 6,
    },
    tweets: [
      { tweetId: "t021a", text: "Our protein interaction model identified 3 novel drug targets for rare diseases. Two are now in preclinical validation with pharma partners.", likes: 345, retweets: 56, replies: 28, views: 18000, isRetweet: false, isReply: false, createdAt: "2026-02-16T10:00:00Z" },
      { tweetId: "t021b", text: "Fine-tuned a protein language model on 2M interaction pairs. It predicts binding affinity with 0.91 correlation to experimental data. Paper submitted.", likes: 234, retweets: 45, replies: 19, views: 12000, isRetweet: false, isReply: false, createdAt: "2026-02-08T14:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_022",
      username: "amy_automl",
      displayName: "Amy Foster",
      bio: "AutoML for everyone. No-code AI model training. Making ML accessible to non-engineers.",
      avatarUrl: avatar("amy"),
      followerCount: 3900,
      followingCount: 650,
      tweetCount: 1800,
      accountCreatedAt: "2022-01-20T00:00:00Z",
      pipelineStage: "discovered",
      overallScore: 62,
      builderScore: 68,
      authenticityScore: 60,
      growthScore: 58,
      redFlagScore: 10,
    },
    tweets: [
      { tweetId: "t022a", text: "Launched our no-code ML platform. Upload a CSV, describe what you want to predict, get a deployed model in 5 minutes. No coding required.", likes: 189, retweets: 34, replies: 19, views: 9800, isRetweet: false, isReply: false, createdAt: "2026-02-15T09:00:00Z" },
      { tweetId: "t022b", text: "Biggest learning from building no-code tools: your users don't want to learn ML concepts. They want answers to business questions. Abstract everything.", likes: 234, retweets: 45, replies: 23, views: 12000, isRetweet: false, isReply: false, createdAt: "2026-02-07T13:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_023",
      username: "carlos_cv",
      displayName: "Carlos Mendez",
      bio: "Computer vision for retail. Smart checkout, inventory tracking, loss prevention. Ex-Amazon Go.",
      avatarUrl: avatar("carlos"),
      followerCount: 5800,
      followingCount: 470,
      tweetCount: 1500,
      accountCreatedAt: "2020-09-15T00:00:00Z",
      pipelineStage: "contacted",
      overallScore: 75,
      builderScore: 80,
      authenticityScore: 74,
      growthScore: 70,
      redFlagScore: 7,
    },
    tweets: [
      { tweetId: "t023a", text: "Our CV system now tracks inventory with 99.2% accuracy across 200 stores. Shrinkage detection caught $2M in losses last quarter for one client.", likes: 345, retweets: 56, replies: 28, views: 18000, isRetweet: false, isReply: false, createdAt: "2026-02-17T10:00:00Z" },
      { tweetId: "t023b", text: "Built a real-time product recognition system that works with any store layout. No per-store training needed. Transfer learning + few-shot adaptation.", likes: 234, retweets: 45, replies: 19, views: 12000, isRetweet: false, isReply: false, createdAt: "2026-02-10T14:00:00Z" },
      { tweetId: "t023c", text: "Retail AI is unglamorous but incredibly sticky. Once you're in the supply chain, switching costs are enormous. Moat built on integration depth.", likes: 178, retweets: 34, replies: 14, views: 9000, isRetweet: false, isReply: false, createdAt: "2026-02-03T09:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_024",
      username: "zoe_dataeng",
      displayName: "Zoe Nakamura",
      bio: "Data engineering for AI. Building pipelines that don't break at 3am. Opinions are my own.",
      avatarUrl: avatar("zoe"),
      followerCount: 2200,
      followingCount: 340,
      tweetCount: 900,
      accountCreatedAt: "2022-04-10T00:00:00Z",
      pipelineStage: "discovered",
      overallScore: 55,
      builderScore: 60,
      authenticityScore: 58,
      growthScore: 48,
      redFlagScore: 5,
    },
    tweets: [
      { tweetId: "t024a", text: "Built a data pipeline orchestrator that auto-heals when sources change schema. No more 3am PagerDuty alerts for broken ETL jobs.", likes: 123, retweets: 19, replies: 14, views: 6200, isRetweet: false, isReply: false, createdAt: "2026-02-14T10:00:00Z" },
      { tweetId: "t024b", text: "The unsexy truth about AI products: 80% of the engineering work is data wrangling. The model is the easy part.", likes: 234, retweets: 45, replies: 23, views: 12000, isRetweet: false, isReply: false, createdAt: "2026-02-06T15:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_025",
      username: "mike_genart",
      displayName: "Mike Artisan",
      bio: "AI generative art. Pushing the boundaries of creativity with diffusion models. Artist + engineer.",
      avatarUrl: avatar("mike"),
      followerCount: 18000,
      followingCount: 2300,
      tweetCount: 5600,
      accountCreatedAt: "2019-05-10T00:00:00Z",
      pipelineStage: "discovered",
      overallScore: 58,
      builderScore: 55,
      authenticityScore: 65,
      growthScore: 60,
      redFlagScore: 15,
    },
    tweets: [
      { tweetId: "t025a", text: "Created a custom LoRA that generates photorealistic product mockups from text descriptions. Saves brands weeks of photoshoot planning.", likes: 890, retweets: 134, replies: 67, views: 45000, isRetweet: false, isReply: false, createdAt: "2026-02-18T15:00:00Z" },
      { tweetId: "t025b", text: "AI art isn't replacing artists. It's giving us superpowers. Made more art in the last year than the previous decade combined.", likes: 567, retweets: 89, replies: 45, views: 29000, isRetweet: false, isReply: false, createdAt: "2026-02-11T12:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_026",
      username: "hannah_secai",
      displayName: "Hannah Brooks",
      bio: "AI for cybersecurity. Detecting threats faster than humans. SOC automation. CISO whisperer.",
      avatarUrl: avatar("hannah"),
      followerCount: 4300,
      followingCount: 510,
      tweetCount: 1600,
      accountCreatedAt: "2021-06-08T00:00:00Z",
      pipelineStage: "discovered",
      overallScore: 69,
      builderScore: 74,
      authenticityScore: 68,
      growthScore: 64,
      redFlagScore: 7,
    },
    tweets: [
      { tweetId: "t026a", text: "Our AI SOC analyst processes 10,000 alerts/day and escalates only the 15 that actually matter. False positive reduction: 97%. Security teams can finally focus.", likes: 234, retweets: 45, replies: 23, views: 12000, isRetweet: false, isReply: false, createdAt: "2026-02-16T11:00:00Z" },
      { tweetId: "t026b", text: "Shipped a threat detection model that identifies novel attack patterns by understanding code semantics, not just signatures. Caught a zero-day in beta testing.", likes: 345, retweets: 56, replies: 28, views: 18000, isRetweet: false, isReply: false, createdAt: "2026-02-09T10:00:00Z" },
    ],
  },
  {
    candidate: {
      twitterId: "seed_027",
      username: "liam_fintech_ai",
      displayName: "Liam O'Brien",
      bio: "AI for fintech. Fraud detection, risk scoring, automated compliance. Making finance safer with ML.",
      avatarUrl: avatar("liam"),
      followerCount: 6100,
      followingCount: 480,
      tweetCount: 1900,
      accountCreatedAt: "2020-12-15T00:00:00Z",
      pipelineStage: "in_conversation",
      overallScore: 81,
      builderScore: 85,
      authenticityScore: 79,
      growthScore: 77,
      redFlagScore: 6,
    },
    tweets: [
      { tweetId: "t027a", text: "Our fraud detection model saved a neobank $4.2M in Q4. Uses graph neural networks to spot coordinated fraud rings that rule-based systems miss entirely.", likes: 456, retweets: 67, replies: 34, views: 23000, isRetweet: false, isReply: false, createdAt: "2026-02-18T10:00:00Z" },
      { tweetId: "t027b", text: "Built a real-time transaction risk scorer that processes 50K transactions/second with <10ms latency. The secret: model distillation + custom inference runtime.", likes: 234, retweets: 45, replies: 19, views: 12000, isRetweet: false, isReply: false, createdAt: "2026-02-11T13:00:00Z" },
      { tweetId: "t027c", text: "Compliance automation is a goldmine. Banks spend billions on compliance staff. AI can automate 60% of their work. We're proving it.", likes: 345, retweets: 56, replies: 28, views: 18000, isRetweet: false, isReply: false, createdAt: "2026-02-04T10:00:00Z" },
    ],
  },
];
